version: '3.8'

services:
  bitcoin-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bitcoin-price-alert
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo